---
title: "Tensor_product_marginal_normals"
author: "Sai Pradeep Peri"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
library(mvtnorm)
library(viridis)
```


Lets start by creating two univariate normal distributions

```{r}
grid <- seq(-4,4, length.out = 100)
x1 <- dnorm(grid)
ggplot(mapping = aes(x = grid, y = x1)) +
  geom_line(color = 'red', size = 2) +
  xlab("X1") +
  ylab("dens") +
  theme_bw()
```

```{r}
x2 <- dnorm(grid)
ggplot(mapping = aes(x = grid, y = x2)) +
  geom_line(color = 'blue', size = 2) +
  xlab("X2") +
  ylab("dens") +
  theme_bw()
```

```{r}
grid_2d <- expand.grid(grid, grid, KEEP.OUT.ATTRS = TRUE)

density_2d <- grid_2d %>% mutate('density' = dmvnorm(grid_2d))

ggplot_obj <- density_2d %>% ggplot(mapping = aes(x = Var1, y =Var2, z = density)) +
  geom_raster(mapping = aes(fill = density)) +
  geom_contour() +
  theme_bw() +
  xlab("X1") +
  ylab("X2") +
  scale_fill_viridis_c()
ggplot_obj
```

```{r}
dmvnorm(as.matrix(grid_2d))
```


```{r}
library(rayshader)
plot_gg(ggplot_obj,multicore=TRUE,width=5,height=5,scale=250,windowsize=c(1400,866),
       theta = 70, zoom = 0.75, phi = 30)
render_snapshot()
```



```{r}
dens_multi_norm <- function(x,y){return(dnorm(x) * dnorm(y))}
z <- outer(grid, grid, dens_multi_norm)
```

```{r}
library(GA)
persp3D(grid, grid, z, phi = 30, theta = 225, expand = 0.4,
        box = TRUE, border = NA, shade = .4, xlab = "x1", ylab = "x2", zlab = "dens")
```








